package core

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/vmihailenco/msgpack/v5"
)

func (c *CSharpFormater) formatRows() {
	c.line = 0
	c.clearData()
	c.BinaryDatas = nil

	data := c.buildMsgpackData()
	bin, err := msgpack.Marshal(data)
	if err != nil {
		c.appendError(fmt.Sprintf("MessagePack序列化失败: %v", err))
		return
	}
	c.BinaryDatas = bin
	c.generateCSharpClass()
}

// buildMsgpackData 构建可被 msgpack 序列化的 Go 数据结构
func (c *CSharpFormater) buildMsgpackData() any {
	if c.Vertical {
		for _, col := range c.Rows {
			c.line++
			return c.buildValue(c.RootField, col)
		}
		return nil
	}

	result := make(map[any]any)
	for _, row := range c.Rows {
		c.line++
		key := row[0]
		if strings.HasPrefix(key, "//") || key == "" {
			continue
		}
		keyField := c.RootField.Vals[0]
		keyVal := c.convertPrimitive(keyField.Type, key)
		result[keyVal] = c.buildValue(c.RootField, row)
	}
	return result
}

// buildValue 递归构建字段值
func (c *CSharpFormater) buildValue(field *Field, row []string) any {
	switch field.Kind {
	case TArray:
		arr := make([]any, 0, len(field.Vals))
		for _, f := range field.Vals {
			arr = append(arr, c.buildValue(f, row))
		}
		return arr
	case TMap:
		m := make(map[any]any)
		for i, k := range field.Keys {
			kval := c.buildValue(k, row)
			v := field.Vals[i]
			vval := c.buildValue(v, row)
			m[kval] = vval
		}
		return m
	case TStruct:
		arr := make([]any, 0, len(field.Vals))
		for _, f := range field.Vals {
			if f.isHitMode(c.mode) {
				arr = append(arr, c.buildValue(f, row))
			}
		}
		return arr
	case TJson:
		s := ""
		if len(row) > field.Index {
			s = row[field.Index]
		}
		if len(s) == 0 {
			return nil
		}
		var result any
		if err := json.Unmarshal([]byte(s), &result); err != nil {
			return nil
		}
		if field.Vtype != nil {
			return c.convertJsonTypedValue(field.Vtype, result)
		}
		return result
	default:
		s := ""
		if len(row) > field.Index {
			s = row[field.Index]
		}
		return c.convertPrimitive(field.Type, s)
	}
}

func (c *CSharpFormater) convertPrimitive(t *Type, val string) any {
	val = strings.TrimSpace(val)
	switch t.Kind {
	case TInt:
		if len(val) == 0 {
			return int64(0)
		}
		v, _ := strconv.ParseInt(val, 10, 64)
		return v
	case TUint:
		if len(val) == 0 {
			return uint64(0)
		}
		v, _ := strconv.ParseUint(val, 10, 64)
		return v
	case TFloat:
		if len(val) == 0 {
			return float64(0)
		}
		v, _ := strconv.ParseFloat(val, 64)
		return v
	case TBool:
		return val == "1" || val == "true"
	case TString:
		return val
	default:
		return val
	}
}

// convertJsonTypedValue 根据声明的 Vtype 对 json.Unmarshal 的结果做类型转换，
// 确保 msgpack 序列化的二进制数据类型与 C# 类定义一致
func (c *CSharpFormater) convertJsonTypedValue(t *Type, val any) any {
	if t == nil || val == nil {
		return val
	}
	switch t.Kind {
	case TInt:
		if f, ok := val.(float64); ok {
			return int64(f)
		}
		return val
	case TUint:
		if f, ok := val.(float64); ok {
			return uint64(f)
		}
		return val
	case TFloat:
		return val
	case TBool:
		return val
	case TString:
		return val
	case TArray:
		if arr, ok := val.([]any); ok {
			result := make([]any, len(arr))
			for i, v := range arr {
				result[i] = c.convertJsonTypedValue(t.Vtype, v)
			}
			return result
		}
		return val
	case TMap:
		if m, ok := val.(map[string]any); ok {
			result := make(map[string]any, len(m))
			for k, v := range m {
				result[k] = c.convertJsonTypedValue(t.Vtype, v)
			}
			return result
		}
		return val
	case TStruct:
		if m, ok := val.(map[string]any); ok && t.Ftypes != nil {
			result := make(map[string]any, len(m))
			for k, v := range m {
				if ft, found := t.Ftypes[k]; found {
					result[k] = c.convertJsonTypedValue(ft, v)
				} else {
					result[k] = v
				}
			}
			return result
		}
		return val
	default:
		return val
	}
}

// generateCSharpClass 生成 C# 类定义并写入 Datas
func (c *CSharpFormater) generateCSharpClass() {
	c.clearData()

	clsName := "T" + toTitle(c.OutName)
	seen := make(map[string]bool)
	nestedClasses := make([]string, 0)
	c.collectNestedClasses(c.RootField, clsName, &nestedClasses, seen)

	c.appendData("// Auto generated by excelparser. DO NOT EDIT!\n")
	c.appendData("using System.Collections.Generic;\n")
	c.appendData("using MessagePack;\n\n")

	c.appendData("[MessagePackObject]\n")
	c.appendData(fmt.Sprintf("public class %s\n", clsName))
	c.appendData("{\n")

	keyIdx := 0
	for _, f := range c.RootField.Vals {
		if f.isHitMode(c.mode) {
			if len(f.Desc) > 0 {
				c.appendData(fmt.Sprintf("    /// <summary>%s</summary>\n", f.Desc))
			}
			c.appendData(fmt.Sprintf("    [Key(%d)]\n", keyIdx))
			typeName := c.csharpTypeName(f.Type, clsName, f.Name)
			c.appendData(fmt.Sprintf("    public %s %s { get; set; }\n\n", typeName, f.Name))
			keyIdx++
		}
	}

	c.appendData("}\n")

	for _, nc := range nestedClasses {
		c.appendData("\n")
		c.appendData(nc)
	}
}

// collectNestedClasses 收集需要生成的嵌套结构体类
func (c *CSharpFormater) collectNestedClasses(field *Field, parentClsName string, out *[]string, seen map[string]bool) {
	for _, f := range field.Vals {
		if !f.isHitMode(c.mode) {
			continue
		}
		c.collectTypeNestedClasses(f.Type, parentClsName, f.Name, f, out, seen)
	}
}

func (c *CSharpFormater) collectTypeNestedClasses(t *Type, parentClsName, fieldName string, field *Field, out *[]string, seen map[string]bool) {
	switch t.Kind {
	case TArray:
		if t.Vtype != nil && len(field.Vals) > 0 {
			c.collectTypeNestedClasses(t.Vtype, parentClsName, fieldName, field.Vals[0], out, seen)
		}
	case TMap:
		if t.Vtype != nil && len(field.Vals) > 0 {
			c.collectTypeNestedClasses(t.Vtype, parentClsName, fieldName, field.Vals[0], out, seen)
		}
	case TStruct:
		clsName := c.structClassName(t, parentClsName, fieldName)
		if seen[clsName] {
			return
		}
		seen[clsName] = true

		var sb strings.Builder
		sb.WriteString("[MessagePackObject]\n")
		sb.WriteString(fmt.Sprintf("public class %s\n", clsName))
		sb.WriteString("{\n")

		keyIdx := 0
		for _, sf := range field.Vals {
			if sf.isHitMode(c.mode) {
				if len(sf.Desc) > 0 {
					sb.WriteString(fmt.Sprintf("    /// <summary>%s</summary>\n", sf.Desc))
				}
				sb.WriteString(fmt.Sprintf("    [Key(%d)]\n", keyIdx))
				typeName := c.csharpTypeName(sf.Type, clsName, sf.Name)
				sb.WriteString(fmt.Sprintf("    public %s %s { get; set; }\n\n", typeName, sf.Name))
				keyIdx++
			}
		}
		sb.WriteString("}\n")
		*out = append(*out, sb.String())

		for _, sf := range field.Vals {
			if sf.isHitMode(c.mode) {
				c.collectTypeNestedClasses(sf.Type, clsName, sf.Name, sf, out, seen)
			}
		}
	case TJson:
		if t.Vtype != nil {
			c.collectJsonTypeClasses(t.Vtype, parentClsName, fieldName, out, seen)
		}
	}
}

// collectJsonTypeClasses 从 Type 树（Ftypes）收集 JSON 内嵌结构体的 C# 类定义
// JSON 数据经 json.Unmarshal 后为 map[string]any，msgpack 序列化为字符串键 map，
// 因此生成的 C# 类使用 [Key("fieldName")] 字符串键
func (c *CSharpFormater) collectJsonTypeClasses(t *Type, parentClsName, fieldName string, out *[]string, seen map[string]bool) {
	switch t.Kind {
	case TArray:
		if t.Vtype != nil {
			c.collectJsonTypeClasses(t.Vtype, parentClsName, fieldName, out, seen)
		}
	case TMap:
		if t.Vtype != nil {
			c.collectJsonTypeClasses(t.Vtype, parentClsName, fieldName, out, seen)
		}
	case TStruct:
		clsName := c.structClassName(t, parentClsName, fieldName)
		if seen[clsName] {
			return
		}
		seen[clsName] = true

		names := make([]string, 0, len(t.Ftypes))
		for name := range t.Ftypes {
			names = append(names, name)
		}
		sort.Strings(names)

		var sb strings.Builder
		sb.WriteString("[MessagePackObject]\n")
		sb.WriteString(fmt.Sprintf("public class %s\n", clsName))
		sb.WriteString("{\n")

		for _, fname := range names {
			ftype := t.Ftypes[fname]
			sb.WriteString(fmt.Sprintf("    [Key(\"%s\")]\n", fname))
			typeName := c.csharpTypeName(ftype, clsName, fname)
			sb.WriteString(fmt.Sprintf("    public %s %s { get; set; }\n\n", typeName, fname))
		}
		sb.WriteString("}\n")
		*out = append(*out, sb.String())

		for _, fname := range names {
			ftype := t.Ftypes[fname]
			c.collectJsonTypeClasses(ftype, clsName, fname, out, seen)
		}
	}
}

func (c *CSharpFormater) structClassName(t *Type, parentClsName, fieldName string) string {
	if len(t.Aname) > 0 {
		return toTitle(t.Aname)
	}
	return parentClsName + toTitle(fieldName)
}

// csharpTypeName 将内部 Type 映射为 C# 类型名
func (c *CSharpFormater) csharpTypeName(t *Type, parentClsName, fieldName string) string {
	switch t.Kind {
	case TInt:
		return "int"
	case TUint:
		return "uint"
	case TFloat:
		return "float"
	case TBool:
		return "bool"
	case TString:
		return "string"
	case TArray:
		if t.Vtype != nil {
			elemType := c.csharpTypeName(t.Vtype, parentClsName, fieldName)
			return elemType + "[]"
		}
		return "object[]"
	case TMap:
		kType := "object"
		vType := "object"
		if t.Ktype != nil {
			kType = c.csharpTypeName(t.Ktype, parentClsName, fieldName)
		}
		if t.Vtype != nil {
			vType = c.csharpTypeName(t.Vtype, parentClsName, fieldName)
		}
		return fmt.Sprintf("Dictionary<%s, %s>", kType, vType)
	case TStruct:
		return c.structClassName(t, parentClsName, fieldName)
	case TJson:
		if t.Vtype != nil {
			return c.csharpTypeName(t.Vtype, parentClsName, fieldName)
		}
		return "object"
	case TAny:
		return "object"
	default:
		return "object"
	}
}
