// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function GetConfig() {
    return $Call.ByID(120325808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * 获取翻译列表
 * @returns {$CancellablePromise<string[]>}
 */
export function GetTranslationList() {
    return $Call.ByID(3970690021).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.XlsxListItem[]>}
 */
export function GetXlsxList(path) {
    return $Call.ByID(1034675581, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFile(path) {
    return $Call.ByID(2551180612, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileDirectory(path) {
    return $Call.ByID(4104698063, path);
}

/**
 * @param {$models.AppConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(1258018725, config);
}

/**
 * 选择目录并更新核心路径
 * @param {number} pathType
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(pathType, title) {
    return $Call.ByID(2889033537, pathType, title);
}

/**
 * 设置导出选项
 * @param {number} flagType
 * @param {boolean} flagVal
 * @returns {$CancellablePromise<void>}
 */
export function SetExportFlag(flagType, flagVal) {
    return $Call.ByID(3972833466, flagType, flagVal);
}

/**
 * 设置导出格式
 * @param {string} target
 * @param {string[]} formats
 * @returns {$CancellablePromise<void>}
 */
export function SetExportFormat(target, formats) {
    return $Call.ByID(2809236059, target, formats);
}

/**
 * 设置i18n语言
 * @param {string} lang
 * @returns {$CancellablePromise<void>}
 */
export function SetI18nLang(lang) {
    return $Call.ByID(1737489462, lang);
}

/**
 * 开始导出
 * @returns {$CancellablePromise<void>}
 */
export function StartExport() {
    return $Call.ByID(1898708896);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.XlsxListItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
