// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * 配置结构
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("config_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config_path"] = "";
        }
        if (!("output_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_path"] = "";
        }
        if (!("i18n_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["i18n_path"] = "";
        }
        if (!("i18n_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["i18n_lang"] = "";
        }
        if (!("server_fmts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["server_fmts"] = [];
        }
        if (!("client_fmts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["client_fmts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("server_fmts" in $$parsedSource) {
            $$parsedSource["server_fmts"] = $$createField4_0($$parsedSource["server_fmts"]);
        }
        if ("client_fmts" in $$parsedSource) {
            $$parsedSource["client_fmts"] = $$createField5_0($$parsedSource["client_fmts"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class ExportProgressEvent {
    /**
     * Creates a new ExportProgressEvent instance.
     * @param {Partial<ExportProgressEvent>} [$$source = {}] - The source object to create the ExportProgressEvent.
     */
    constructor($$source = {}) {
        if (!("stage" in $$source)) {
            /**
             * 阶段：start, finish, error, done
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 文件名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 文件完整路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 导出状态：0=空闲, 1=导出中, 2=成功, 3=失败, 4=跳过
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 结果消息，成功时可为空，失败时包含错误信息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * 所有错误消息列表
             * @member
             * @type {string[]}
             */
            this["messages"] = [];
        }
        if (!("seq" in $$source)) {
            /**
             * 事件序列号，用于前端排序
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportProgressEvent}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField5_0($$parsedSource["messages"]);
        }
        return new ExportProgressEvent(/** @type {Partial<ExportProgressEvent>} */($$parsedSource));
    }
}

export class XlsxListItem {
    /**
     * Creates a new XlsxListItem instance.
     * @param {Partial<XlsxListItem>} [$$source = {}] - The source object to create the XlsxListItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("need_parse" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["need_parse"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new XlsxListItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {XlsxListItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new XlsxListItem(/** @type {Partial<XlsxListItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
