-- Auto generated by excelparser. DO NOT EDIT!

---system@系统
---@class TSystem
---@field key1 integer 字段1
---@field key2 string 字段2
---@field key3 boolean 字段3
---@field key4 integer 字段4
---@field key5 number 字段5
---@field key6 integer[] 简单字典
---@field key7 integer[][] 二维数组

---@type TSystem
local t = {
  key1 = 1,
  key2 = "fuckyou",
  key3 = false,
  key4 = 4,
  key5 = 3.14,
  key6 = {
    [1] = 4,
    [2] = 5
  },
  key7 = {
    [1] = {
      [1] = 1,
      [2] = 2,
      [3] = 3
    },
    [2] = {
      [1] = 4,
      [2] = 5,
      [3] = 6
    }
  }
}
return t