-- Auto generated by excelparser. DO NOT EDIT!

---道具\item@道具
---@class TItem
---@field id integer 配置唯一id
---@field name string 道具名

---@type table<integer, TItem>
local t = {
  [1001] = {
    id = 1001,
    name = "道具1"
  },
  [1002] = {
    id = 1002,
    name = "道具2"
  },
  [1003] = {
    id = 1003,
    name = "道具3"
  },
  [1004] = {
    id = 1004,
    name = "道具4"
  }
}
return t